import Head from 'next/head';
import css from './Home.module.scss';
import Link from 'next/link';

export default function Page() {
  return (
    <div className={css.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/front/public/favicon.ico" />
      </Head>

      <h1 className={css.title}>
        Welcome to <Link href={'/login'}>HETIC Messenger!</Link>
      </h1>
    </div>
  );
}
